when:
  - event: manual
  - event: pull_request

steps:
  - name: tox
    image: ghcr.io/astral-sh/uv:python3.14-trixie-slim
    commands:
      # Install chrome
      - sudo apt update
      - sudo apt install extrepo -y
      - sudo sed -i 's/# - non-free/- non-free/' /etc/extrepo/config.yaml
      - sudo extrepo enable google_chrome
      - sudo apt update
      - sudo apt install google-chrome-stable -y
      # Run tox
      - uv tool install tox --with tox-uv
      - tox
